const Leagues = [
  { id: 12, title: 'Alemão' },
  { id: 13, title: 'Amistosos' },
  { id: 28, title: 'Baiano' },
  { id: 30, title: 'Brasileirão' },
  { id: 34, title: 'Carioca' },
  { id: 36, title: 'Cearense' },
  { id: 39, title: 'Copa América' },
  { id: 41, title: 'Copa da Alemanha' },
  { id: 42, title: 'Copa da França (não aparece)' },
  { id: 43, title: 'Copa da Inglaterra' },
  { id: 44, title: 'Copa da Itália' },
  { id: 48, title: 'Copa do Brasil' },
  { id: 54, title: 'Copa do Mundo Feminina' },
  { id: 55, title: 'Copa do Nordeste' },
  { id: 56, title: 'Copa do Rei' },
  { id: 58, title: 'Copa São Paulo' },
  { id: 59, title: 'Copa Sul-americana' },
  { id: 60, title: 'Eliminatŕias Africanas' },
  { id: 63, title: 'Eliminatórias Asiáticas' },
  { id: 71, title: 'Eliminatórias da Eurocopa' },
  { id: 72, title: 'Espanhol' },
  { id: 76, title: 'França' },
  { id: 77, title: 'Gaúcho' },
  { id: 79, title: 'Inglês' },
  { id: 81, title: 'Italiano' },
  { id: 82, title: 'Libertadores' },
  { id: 83, title: 'Liga dos Campeões' },
  { id: 84, title: 'Liga Europa' },
  { id: 86, title: 'Mineiro' },
  { id: 87, title: 'Mundial de Clubes' },
  { id: 103, title: 'Paranaense' },
  { id: 104, title: 'Paulista' },
  { id: 107, title: 'Pernambucano' },
  { id: 110, title: 'Recopa Sul-americana' },
  { id: 112, title: 'Série B' },
  { id: 113, title: 'Série C' },
  { id: 114, title: 'Série D' },
  { id: 116, title: 'Sul-americano Sub-20' },
  { id: 117, title: 'Supercopa da Espanha' },
  { id: 118, title: 'Supercopa da Europa' },
  { id: 119, title: 'Supercopa da Inglaterra' },
  { id: 120, title: 'Supercopa da Itália' },
  { id: 142, title: 'Amistosos da Seleção Brasileira' },
  { id: 143, title: 'Supercopa da Alemanha' },
  { id: 144, title: 'Supercopa da França' },
  { id: 147, title: 'Copa Suruga' },
  { id: 148, title: 'Copa da Liga Francesa' },
  { id: 149, title: 'Copa da Liga Inglesa' },
  { id: 160, title: 'Liga das Nações' },
  { id: 161, title: 'Flórida Cup' }
]

export default Leagues
